spring.application.name=campy

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/campy_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=NxD@49#jKw!rMv7Up2zLt$gQpY%1fA3eTb8CkD$HzLwRm


# 전체 로그 레벨은 INFO
logging.level.root=info
# 내가 만든 코드(com.example.campy) INFO
logging.level.com.example.campy=info
# Spring MVC 요청 처리 흐름 로그 (컨트롤러 매핑 등 확인 가능)
logging.level.org.springframework.web.servlet=debug
# ibernate 바인딩 로그 (MySQL 파라미터 확인, 개발 중에만 TRACE)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
# SQL 쿼리 자체를 콘솔에 출력
logging.level.org.hibernate.SQL=debug

# 콘솔 로그 출력 포맷 (간결 + 필요한 정보 포함)
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
# 로그 인코딩 (한글 깨짐 방지)
logging.file.encoding=UTF-8
logging.encoding.charset=UTF-8


upload.path=D:/campy/uploads

spring.profiles.active=dev